'use strict';
function assert(ok,message){if(!ok){const e=new Error(message);e.status=422;throw e;}}
function context(user,tenantId,roles){assert(user&&user.id,'authenticated actor required');assert(tenantId,'x-tenant-id is required');if(user.tenantId||user.tenant_id)assert((user.tenantId||user.tenant_id)===tenantId,'tenant mismatch');const role=user.role||'analyst';assert(roles.includes(role),'role not authorized');return{tenantId,actorId:String(user.id),role};}
function validateApplication(input){assert(/^[A-Za-z0-9._:-]{3,128}$/.test(input.idempotencyKey||''),'invalid idempotencyKey');assert(String(input.applicantReference||'').trim().length>=3,'applicantReference is required');assert(String(input.jurisdiction||'').trim().length>=2,'jurisdiction is required');assert(Number.isSafeInteger(input.requestedAmountCents)&&input.requestedAmountCents>0,'requestedAmountCents must be positive');assert(/^https:\/\/|^s3:\/\/|^gs:\/\//.test(input.sourceSnapshotUri||''),'verified source snapshot is required');assert(/^[a-f0-9]{64}$/i.test(input.sourceSnapshotSha256||''),'source snapshot digest is invalid');assert(String(input.consentReference||'').trim().length>=3&&Number.isFinite(Date.parse(input.consentRecordedAt)),'valid consent evidence is required');return input;}
function evaluatePolicy(input,policy){assert(policy&&policy.rules,'approved policy is required');const rules=policy.rules;const results=[];for(const rule of rules.required||[]){const value=input[rule.field];const passed=rule.operator==='gte'?Number(value)>=Number(rule.value):rule.operator==='lte'?Number(value)<=Number(rule.value):rule.operator==='eq'?value===rule.value:false;results.push({code:rule.code,passed,observed:value,threshold:rule.value});}const failed=results.filter(r=>!r.passed);return{ruleResults:results,recommendation:failed.length?'review':'approve',reasonCodes:failed.map(r=>r.code)};}
function validateDecision({actor,application,evaluation,decision,reasonCodes,explanation,policy}){assert(actor&&['underwriter','credit_officer','admin'].includes(actor.role),'human credit authority is required');assert(application&&['verified','policy_evaluation','human_review','disputed'].includes(application.status),'application is not decisionable');assert(evaluation&&policy&&evaluation.policy_version_id===policy.id,'evaluation must reference the approved policy');assert(['approved','declined','withdrawn','corrected'].includes(decision),'decision is invalid');if(decision==='declined'){assert(Array.isArray(reasonCodes)&&reasonCodes.length>0,'decline requires adverse-action reason codes');assert(String(explanation||'').trim().length>=20,'decline requires a specific explanation');}return true;}
function contactAllowed({consent,jurisdictionRule,now=new Date()}){assert(consent===true,'contact consent is required');assert(jurisdictionRule&&Number.isInteger(jurisdictionRule.startHour)&&Number.isInteger(jurisdictionRule.endHour),'jurisdiction contact rule is required');const hour=now.getUTCHours();return hour>=jurisdictionRule.startHour&&hour<jurisdictionRule.endHour;}
function evaluationDisposition(metrics,thresholds){const failures=[];if(metrics.brierScore>thresholds.maxBrierScore)failures.push('calibration');if(metrics.driftPsi>thresholds.maxDriftPsi)failures.push('drift');for(const [group,value] of Object.entries(metrics.selectionRateRatios||{}))if(value<thresholds.minSelectionRateRatio)failures.push(`fairness:${group}`);return{disposition:failures.length?'blocked':'pass',failures};}
module.exports={context,validateApplication,evaluatePolicy,validateDecision,contactAllowed,evaluationDisposition};
