require('dotenv').config({ path: require('path').join(__dirname, '../../../.env') });
const bcrypt = require('bcryptjs');
const { sequelize, User, Applicant, Assessment, Portfolio, FraudCase, RegulatoryReport, Collateral, EarlyWarning, PricingModel } = require('../models');

async function seed() {
  try {
    await sequelize.authenticate();
    console.log('Connected to database');
    await sequelize.sync({ force: true });
    console.log('Tables created');

    // Seed Users
    const hashedPassword = await bcrypt.hash('admin123', 10);
    await User.bulkCreate([
      { email: 'admin@creditrisk.ai', password: hashedPassword, name: 'Admin User', role: 'admin' },
      { email: 'analyst@creditrisk.ai', password: hashedPassword, name: 'Risk Analyst', role: 'analyst' },
    ]);
    console.log('Users seeded');

    // Seed Applicants (16 items)
    const applicants = await Applicant.bulkCreate([
      { firstName: 'James', lastName: 'Morrison', email: 'james.m@email.com', phone: '555-0101', ssn: '***-**-1234', dateOfBirth: '1985-03-15', address: '123 Oak St, New York, NY 10001', employmentStatus: 'Full-time', annualIncome: 95000, employerName: 'Tech Corp', yearsEmployed: 5.5, creditScore: 750, existingDebt: 25000, monthlyExpenses: 3200, bankruptcyHistory: false, status: 'approved' },
      { firstName: 'Sarah', lastName: 'Chen', email: 'sarah.c@email.com', phone: '555-0102', ssn: '***-**-2345', dateOfBirth: '1990-07-22', address: '456 Maple Ave, San Francisco, CA 94102', employmentStatus: 'Full-time', annualIncome: 125000, employerName: 'Finance Inc', yearsEmployed: 3.0, creditScore: 810, existingDebt: 15000, monthlyExpenses: 4500, bankruptcyHistory: false, status: 'approved' },
      { firstName: 'Michael', lastName: 'Johnson', email: 'michael.j@email.com', phone: '555-0103', ssn: '***-**-3456', dateOfBirth: '1978-11-08', address: '789 Pine Rd, Chicago, IL 60601', employmentStatus: 'Self-employed', annualIncome: 180000, employerName: 'Johnson Consulting', yearsEmployed: 12.0, creditScore: 680, existingDebt: 95000, monthlyExpenses: 6800, bankruptcyHistory: false, status: 'review' },
      { firstName: 'Emily', lastName: 'Williams', email: 'emily.w@email.com', phone: '555-0104', ssn: '***-**-4567', dateOfBirth: '1992-04-30', address: '321 Elm St, Austin, TX 73301', employmentStatus: 'Full-time', annualIncome: 72000, employerName: 'Healthcare Plus', yearsEmployed: 2.5, creditScore: 720, existingDebt: 30000, monthlyExpenses: 2800, bankruptcyHistory: false, status: 'pending' },
      { firstName: 'Robert', lastName: 'Davis', email: 'robert.d@email.com', phone: '555-0105', ssn: '***-**-5678', dateOfBirth: '1970-09-12', address: '654 Birch Ln, Miami, FL 33101', employmentStatus: 'Retired', annualIncome: 55000, employerName: 'N/A', yearsEmployed: 0, creditScore: 790, existingDebt: 5000, monthlyExpenses: 2100, bankruptcyHistory: false, status: 'approved' },
      { firstName: 'Lisa', lastName: 'Martinez', email: 'lisa.m@email.com', phone: '555-0106', ssn: '***-**-6789', dateOfBirth: '1988-01-25', address: '987 Cedar Dr, Seattle, WA 98101', employmentStatus: 'Full-time', annualIncome: 88000, employerName: 'Amazon', yearsEmployed: 4.0, creditScore: 695, existingDebt: 45000, monthlyExpenses: 3500, bankruptcyHistory: false, status: 'review' },
      { firstName: 'David', lastName: 'Brown', email: 'david.b@email.com', phone: '555-0107', ssn: '***-**-7890', dateOfBirth: '1995-06-18', address: '147 Walnut St, Denver, CO 80201', employmentStatus: 'Part-time', annualIncome: 35000, employerName: 'Retail Store', yearsEmployed: 1.0, creditScore: 580, existingDebt: 20000, monthlyExpenses: 1800, bankruptcyHistory: true, status: 'denied' },
      { firstName: 'Jennifer', lastName: 'Taylor', email: 'jennifer.t@email.com', phone: '555-0108', ssn: '***-**-8901', dateOfBirth: '1983-12-03', address: '258 Spruce Ave, Boston, MA 02101', employmentStatus: 'Full-time', annualIncome: 110000, employerName: 'Law Firm LLP', yearsEmployed: 8.0, creditScore: 830, existingDebt: 10000, monthlyExpenses: 4200, bankruptcyHistory: false, status: 'approved' },
      { firstName: 'William', lastName: 'Anderson', email: 'william.a@email.com', phone: '555-0109', ssn: '***-**-9012', dateOfBirth: '1975-08-21', address: '369 Ash St, Portland, OR 97201', employmentStatus: 'Full-time', annualIncome: 78000, employerName: 'Manufacturing Co', yearsEmployed: 15.0, creditScore: 740, existingDebt: 35000, monthlyExpenses: 3000, bankruptcyHistory: false, status: 'approved' },
      { firstName: 'Amanda', lastName: 'Garcia', email: 'amanda.g@email.com', phone: '555-0110', ssn: '***-**-0123', dateOfBirth: '1991-02-14', address: '741 Hickory Rd, Phoenix, AZ 85001', employmentStatus: 'Full-time', annualIncome: 65000, employerName: 'Education Dept', yearsEmployed: 3.5, creditScore: 710, existingDebt: 50000, monthlyExpenses: 2600, bankruptcyHistory: false, status: 'pending' },
      { firstName: 'Christopher', lastName: 'Lee', email: 'chris.l@email.com', phone: '555-0111', ssn: '***-**-1235', dateOfBirth: '1987-10-05', address: '852 Poplar St, Atlanta, GA 30301', employmentStatus: 'Self-employed', annualIncome: 150000, employerName: 'Lee Enterprises', yearsEmployed: 7.0, creditScore: 760, existingDebt: 80000, monthlyExpenses: 5500, bankruptcyHistory: false, status: 'approved' },
      { firstName: 'Jessica', lastName: 'White', email: 'jessica.w@email.com', phone: '555-0112', ssn: '***-**-2346', dateOfBirth: '1993-05-28', address: '963 Magnolia Ave, Nashville, TN 37201', employmentStatus: 'Full-time', annualIncome: 58000, employerName: 'Music Label Inc', yearsEmployed: 2.0, creditScore: 640, existingDebt: 28000, monthlyExpenses: 2400, bankruptcyHistory: false, status: 'review' },
      { firstName: 'Daniel', lastName: 'Harris', email: 'daniel.h@email.com', phone: '555-0113', ssn: '***-**-3457', dateOfBirth: '1980-07-16', address: '174 Dogwood Ln, Dallas, TX 75201', employmentStatus: 'Full-time', annualIncome: 92000, employerName: 'Oil & Gas Corp', yearsEmployed: 10.0, creditScore: 770, existingDebt: 40000, monthlyExpenses: 3800, bankruptcyHistory: false, status: 'approved' },
      { firstName: 'Maria', lastName: 'Rodriguez', email: 'maria.r@email.com', phone: '555-0114', ssn: '***-**-4568', dateOfBirth: '1986-03-09', address: '285 Cypress St, Las Vegas, NV 89101', employmentStatus: 'Unemployed', annualIncome: 0, employerName: 'N/A', yearsEmployed: 0, creditScore: 520, existingDebt: 35000, monthlyExpenses: 1500, bankruptcyHistory: true, status: 'denied' },
      { firstName: 'Thomas', lastName: 'Clark', email: 'thomas.c@email.com', phone: '555-0115', ssn: '***-**-5679', dateOfBirth: '1974-11-22', address: '396 Redwood Dr, San Diego, CA 92101', employmentStatus: 'Full-time', annualIncome: 105000, employerName: 'Defense Contractor', yearsEmployed: 20.0, creditScore: 800, existingDebt: 120000, monthlyExpenses: 4000, bankruptcyHistory: false, status: 'approved' },
      { firstName: 'Ashley', lastName: 'Lewis', email: 'ashley.l@email.com', phone: '555-0116', ssn: '***-**-6780', dateOfBirth: '1997-08-07', address: '507 Sequoia Blvd, Minneapolis, MN 55401', employmentStatus: 'Full-time', annualIncome: 48000, employerName: 'Startup Inc', yearsEmployed: 1.5, creditScore: 670, existingDebt: 22000, monthlyExpenses: 2000, bankruptcyHistory: false, status: 'pending' },
    ]);
    console.log('Applicants seeded');

    // Seed Assessments (16 items)
    await Assessment.bulkCreate([
      { applicantId: 1, riskScore: 25, riskCategory: 'low', creditLimit: 50000, interestRate: 5.5, approvalStatus: 'approved', loanType: 'Personal', loanAmount: 30000, loanTerm: 60, debtToIncomeRatio: 26.3, aiAnalysis: 'Strong credit profile with stable employment history', aiRecommendation: 'Approve with standard terms', assessedBy: 'AI System' },
      { applicantId: 2, riskScore: 15, riskCategory: 'low', creditLimit: 75000, interestRate: 4.2, approvalStatus: 'approved', loanType: 'Mortgage', loanAmount: 450000, loanTerm: 360, debtToIncomeRatio: 12.0, aiAnalysis: 'Excellent credit score and high income', aiRecommendation: 'Approve with preferred rate', assessedBy: 'AI System' },
      { applicantId: 3, riskScore: 55, riskCategory: 'medium', creditLimit: 40000, interestRate: 8.5, approvalStatus: 'review', loanType: 'Business', loanAmount: 200000, loanTerm: 120, debtToIncomeRatio: 52.8, aiAnalysis: 'High DTI ratio despite good income', aiRecommendation: 'Manual review required', assessedBy: 'AI System' },
      { applicantId: 4, riskScore: 35, riskCategory: 'low', creditLimit: 35000, interestRate: 6.0, approvalStatus: 'approved', loanType: 'Auto', loanAmount: 28000, loanTerm: 72, debtToIncomeRatio: 41.7, aiAnalysis: 'Good credit with moderate debt', aiRecommendation: 'Approve with monitoring', assessedBy: 'AI System' },
      { applicantId: 5, riskScore: 20, riskCategory: 'low', creditLimit: 30000, interestRate: 5.0, approvalStatus: 'approved', loanType: 'Personal', loanAmount: 15000, loanTerm: 36, debtToIncomeRatio: 9.1, aiAnalysis: 'Low risk retiree with excellent credit history', aiRecommendation: 'Approve', assessedBy: 'AI System' },
      { applicantId: 6, riskScore: 48, riskCategory: 'medium', creditLimit: 25000, interestRate: 7.8, approvalStatus: 'review', loanType: 'Personal', loanAmount: 20000, loanTerm: 48, debtToIncomeRatio: 51.1, aiAnalysis: 'Borderline DTI with fair credit score', aiRecommendation: 'Review with conditions', assessedBy: 'AI System' },
      { applicantId: 7, riskScore: 82, riskCategory: 'high', creditLimit: 5000, interestRate: 18.0, approvalStatus: 'denied', loanType: 'Personal', loanAmount: 10000, loanTerm: 24, debtToIncomeRatio: 57.1, aiAnalysis: 'High risk - low income, bankruptcy history', aiRecommendation: 'Deny', assessedBy: 'AI System' },
      { applicantId: 8, riskScore: 12, riskCategory: 'low', creditLimit: 80000, interestRate: 4.0, approvalStatus: 'approved', loanType: 'Mortgage', loanAmount: 350000, loanTerm: 360, debtToIncomeRatio: 9.1, aiAnalysis: 'Premium credit profile', aiRecommendation: 'Approve with best rate', assessedBy: 'AI System' },
      { applicantId: 9, riskScore: 30, riskCategory: 'low', creditLimit: 40000, interestRate: 5.8, approvalStatus: 'approved', loanType: 'Home Equity', loanAmount: 50000, loanTerm: 180, debtToIncomeRatio: 44.9, aiAnalysis: 'Long employment tenure, good credit', aiRecommendation: 'Approve', assessedBy: 'AI System' },
      { applicantId: 10, riskScore: 42, riskCategory: 'medium', creditLimit: 20000, interestRate: 7.2, approvalStatus: 'review', loanType: 'Student', loanAmount: 35000, loanTerm: 120, debtToIncomeRatio: 76.9, aiAnalysis: 'High student debt relative to income', aiRecommendation: 'Conditional approval', assessedBy: 'AI System' },
      { applicantId: 11, riskScore: 28, riskCategory: 'low', creditLimit: 60000, interestRate: 5.5, approvalStatus: 'approved', loanType: 'Business', loanAmount: 100000, loanTerm: 84, debtToIncomeRatio: 53.3, aiAnalysis: 'Strong business revenue, good credit', aiRecommendation: 'Approve with business review', assessedBy: 'AI System' },
      { applicantId: 12, riskScore: 58, riskCategory: 'medium', creditLimit: 15000, interestRate: 9.5, approvalStatus: 'review', loanType: 'Personal', loanAmount: 12000, loanTerm: 36, debtToIncomeRatio: 48.3, aiAnalysis: 'Below average credit, moderate income', aiRecommendation: 'Review with higher rate', assessedBy: 'AI System' },
      { applicantId: 13, riskScore: 22, riskCategory: 'low', creditLimit: 55000, interestRate: 5.2, approvalStatus: 'approved', loanType: 'Auto', loanAmount: 45000, loanTerm: 60, debtToIncomeRatio: 43.5, aiAnalysis: 'Stable long-term employment, strong credit', aiRecommendation: 'Approve', assessedBy: 'AI System' },
      { applicantId: 14, riskScore: 92, riskCategory: 'critical', creditLimit: 0, interestRate: 0, approvalStatus: 'denied', loanType: 'Personal', loanAmount: 10000, loanTerm: 24, debtToIncomeRatio: 999, aiAnalysis: 'No income, bankruptcy history, very low credit', aiRecommendation: 'Deny - does not meet minimum criteria', assessedBy: 'AI System' },
      { applicantId: 15, riskScore: 18, riskCategory: 'low', creditLimit: 70000, interestRate: 4.5, approvalStatus: 'approved', loanType: 'Mortgage', loanAmount: 500000, loanTerm: 360, debtToIncomeRatio: 114.3, aiAnalysis: 'High mortgage but excellent credit and income', aiRecommendation: 'Approve with standard mortgage terms', assessedBy: 'AI System' },
      { applicantId: 16, riskScore: 52, riskCategory: 'medium', creditLimit: 12000, interestRate: 8.0, approvalStatus: 'review', loanType: 'Personal', loanAmount: 8000, loanTerm: 24, debtToIncomeRatio: 45.8, aiAnalysis: 'Young applicant, limited credit history', aiRecommendation: 'Review - consider secured option', assessedBy: 'AI System' },
    ]);
    console.log('Assessments seeded');

    // Seed Portfolios (16 items)
    await Portfolio.bulkCreate([
      { name: 'Prime Consumer Loans', totalValue: 250000000, totalLoans: 5200, averageRiskScore: 25, defaultRate: 1.2, performanceGrade: 'A', sector: 'Consumer', region: 'Northeast', vintage: '2024-Q1', expectedLoss: 3000000, actualLoss: 2500000, status: 'active' },
      { name: 'Subprime Auto Portfolio', totalValue: 85000000, totalLoans: 3800, averageRiskScore: 62, defaultRate: 8.5, performanceGrade: 'C', sector: 'Auto', region: 'Southeast', vintage: '2023-Q3', expectedLoss: 7225000, actualLoss: 8900000, status: 'active' },
      { name: 'Commercial Real Estate', totalValue: 500000000, totalLoans: 450, averageRiskScore: 35, defaultRate: 2.1, performanceGrade: 'A-', sector: 'CRE', region: 'West', vintage: '2024-Q2', expectedLoss: 10500000, actualLoss: 9800000, status: 'active' },
      { name: 'Small Business Lending', totalValue: 120000000, totalLoans: 2100, averageRiskScore: 45, defaultRate: 4.8, performanceGrade: 'B', sector: 'SMB', region: 'Midwest', vintage: '2023-Q4', expectedLoss: 5760000, actualLoss: 6200000, status: 'active' },
      { name: 'Credit Card Portfolio', totalValue: 180000000, totalLoans: 25000, averageRiskScore: 38, defaultRate: 3.2, performanceGrade: 'B+', sector: 'Revolving', region: 'National', vintage: '2024-Q1', expectedLoss: 5760000, actualLoss: 5100000, status: 'active' },
      { name: 'Student Loan Book', totalValue: 95000000, totalLoans: 4200, averageRiskScore: 42, defaultRate: 5.1, performanceGrade: 'B-', sector: 'Education', region: 'National', vintage: '2022-Q2', expectedLoss: 4845000, actualLoss: 5500000, status: 'active' },
      { name: 'Mortgage Prime', totalValue: 800000000, totalLoans: 3200, averageRiskScore: 20, defaultRate: 0.8, performanceGrade: 'AAA', sector: 'Mortgage', region: 'National', vintage: '2024-Q1', expectedLoss: 6400000, actualLoss: 4800000, status: 'active' },
      { name: 'BNPL Portfolio', totalValue: 45000000, totalLoans: 18000, averageRiskScore: 55, defaultRate: 6.2, performanceGrade: 'C+', sector: 'BNPL', region: 'National', vintage: '2024-Q2', expectedLoss: 2790000, actualLoss: 3100000, status: 'active' },
      { name: 'Equipment Finance', totalValue: 200000000, totalLoans: 850, averageRiskScore: 30, defaultRate: 1.8, performanceGrade: 'A', sector: 'Equipment', region: 'Industrial', vintage: '2023-Q4', expectedLoss: 3600000, actualLoss: 3200000, status: 'active' },
      { name: 'Agricultural Loans', totalValue: 75000000, totalLoans: 620, averageRiskScore: 40, defaultRate: 3.5, performanceGrade: 'B', sector: 'Agriculture', region: 'Midwest', vintage: '2023-Q2', expectedLoss: 2625000, actualLoss: 2800000, status: 'active' },
      { name: 'Fintech Personal Loans', totalValue: 150000000, totalLoans: 12000, averageRiskScore: 48, defaultRate: 5.5, performanceGrade: 'B-', sector: 'Fintech', region: 'National', vintage: '2024-Q1', expectedLoss: 8250000, actualLoss: 7900000, status: 'active' },
      { name: 'Healthcare Receivables', totalValue: 60000000, totalLoans: 1500, averageRiskScore: 28, defaultRate: 1.5, performanceGrade: 'A', sector: 'Healthcare', region: 'National', vintage: '2024-Q2', expectedLoss: 900000, actualLoss: 750000, status: 'active' },
      { name: 'Construction Lending', totalValue: 300000000, totalLoans: 280, averageRiskScore: 52, defaultRate: 4.2, performanceGrade: 'B', sector: 'Construction', region: 'Sun Belt', vintage: '2023-Q3', expectedLoss: 12600000, actualLoss: 13500000, status: 'watch' },
      { name: 'Crypto-Backed Loans', totalValue: 25000000, totalLoans: 500, averageRiskScore: 72, defaultRate: 12.0, performanceGrade: 'D', sector: 'Digital Assets', region: 'National', vintage: '2024-Q1', expectedLoss: 3000000, actualLoss: 4200000, status: 'watch' },
      { name: 'Municipal Bond Fund', totalValue: 400000000, totalLoans: 150, averageRiskScore: 15, defaultRate: 0.3, performanceGrade: 'AAA', sector: 'Municipal', region: 'National', vintage: '2023-Q1', expectedLoss: 1200000, actualLoss: 800000, status: 'active' },
      { name: 'Renewable Energy Finance', totalValue: 180000000, totalLoans: 320, averageRiskScore: 33, defaultRate: 2.0, performanceGrade: 'A-', sector: 'Green Energy', region: 'National', vintage: '2024-Q2', expectedLoss: 3600000, actualLoss: 3000000, status: 'active' },
    ]);
    console.log('Portfolios seeded');

    // Seed Fraud Cases (16 items)
    await FraudCase.bulkCreate([
      { applicantId: 7, caseNumber: 'FRD-2024-001', fraudType: 'Identity Theft', riskLevel: 'high', amount: 45000, description: 'Applicant used stolen identity documents', indicators: '["Mismatched SSN","Address discrepancy","Multiple applications in 24hrs"]', status: 'open', investigator: 'Agent Smith' },
      { applicantId: 14, caseNumber: 'FRD-2024-002', fraudType: 'Income Fraud', riskLevel: 'critical', amount: 120000, description: 'Fabricated employment and income documents', indicators: '["Fake pay stubs","Non-existent employer","Inflated income by 300%"]', status: 'open', investigator: 'Agent Johnson' },
      { applicantId: 3, caseNumber: 'FRD-2024-003', fraudType: 'Application Fraud', riskLevel: 'medium', amount: 75000, description: 'Inconsistencies in multiple loan applications', indicators: '["Different addresses on apps","Varying income claims","Multiple SSNs"]', status: 'investigating', investigator: 'Agent Williams' },
      { applicantId: null, caseNumber: 'FRD-2024-004', fraudType: 'Synthetic Identity', riskLevel: 'high', amount: 200000, description: 'Synthetic identity created from multiple real identities', indicators: '["New SSN with aged credit","No social media presence","PO Box only"]', status: 'open', investigator: 'Agent Brown' },
      { applicantId: null, caseNumber: 'FRD-2024-005', fraudType: 'Account Takeover', riskLevel: 'critical', amount: 89000, description: 'Unauthorized access to existing customer account', indicators: '["IP geolocation mismatch","Device fingerprint change","Rapid transactions"]', status: 'investigating', investigator: 'Agent Davis' },
      { applicantId: 6, caseNumber: 'FRD-2024-006', fraudType: 'Collusion', riskLevel: 'high', amount: 350000, description: 'Suspected collusion between applicant and appraiser', indicators: '["Inflated property value","Appraiser pattern","Related parties"]', status: 'open', investigator: 'Agent Miller' },
      { applicantId: null, caseNumber: 'FRD-2024-007', fraudType: 'Wire Fraud', riskLevel: 'critical', amount: 500000, description: 'Fraudulent wire transfer instructions intercepted', indicators: '["Email spoofing","Changed bank details","Urgency pressure"]', status: 'resolved', investigator: 'Agent Wilson', resolvedAt: '2024-02-15' },
      { applicantId: null, caseNumber: 'FRD-2024-008', fraudType: 'Check Fraud', riskLevel: 'medium', amount: 15000, description: 'Altered checks deposited via mobile', indicators: '["Altered payee","Washed check","Multiple deposits"]', status: 'resolved', investigator: 'Agent Moore', resolvedAt: '2024-01-20' },
      { applicantId: 12, caseNumber: 'FRD-2024-009', fraudType: 'Employment Fraud', riskLevel: 'medium', amount: 25000, description: 'Falsified employment verification documents', indicators: '["Fake company letterhead","Disconnected phone","No web presence"]', status: 'investigating', investigator: 'Agent Taylor' },
      { applicantId: null, caseNumber: 'FRD-2024-010', fraudType: 'Money Laundering', riskLevel: 'critical', amount: 2000000, description: 'Structured deposits and rapid transfers detected', indicators: '["Structuring pattern","Shell companies","Offshore transfers"]', status: 'open', investigator: 'Agent Anderson' },
      { applicantId: null, caseNumber: 'FRD-2024-011', fraudType: 'Phishing', riskLevel: 'high', amount: 67000, description: 'Customer credentials harvested via phishing campaign', indicators: '["Bulk login attempts","Unusual access times","Data exfiltration"]', status: 'investigating', investigator: 'Agent Thomas' },
      { applicantId: null, caseNumber: 'FRD-2024-012', fraudType: 'Insider Threat', riskLevel: 'critical', amount: 180000, description: 'Employee accessed unauthorized customer records', indicators: '["After-hours access","Bulk data export","Policy violations"]', status: 'open', investigator: 'Agent Jackson' },
      { applicantId: 10, caseNumber: 'FRD-2024-013', fraudType: 'Straw Borrower', riskLevel: 'high', amount: 95000, description: 'Third party using applicant as front for loan', indicators: '["Coached responses","Third party payments","Unusual property use"]', status: 'investigating', investigator: 'Agent White' },
      { applicantId: null, caseNumber: 'FRD-2024-014', fraudType: 'Title Fraud', riskLevel: 'high', amount: 420000, description: 'Forged property title documents', indicators: '["Forged signatures","Title irregularities","Rushed closing"]', status: 'open', investigator: 'Agent Harris' },
      { applicantId: null, caseNumber: 'FRD-2024-015', fraudType: 'Card Skimming', riskLevel: 'medium', amount: 32000, description: 'ATM skimming ring detected across multiple locations', indicators: '["Multiple compromised cards","Geographic cluster","Device found"]', status: 'resolved', investigator: 'Agent Martin', resolvedAt: '2024-03-01' },
      { applicantId: 16, caseNumber: 'FRD-2024-016', fraudType: 'First-Party Fraud', riskLevel: 'medium', amount: 8000, description: 'Applicant disputes legitimate transactions', indicators: '["Pattern of disputes","Social media contradictions","Delivery confirmations"]', status: 'investigating', investigator: 'Agent Garcia' },
    ]);
    console.log('Fraud Cases seeded');

    // Seed Regulatory Reports (16 items)
    await RegulatoryReport.bulkCreate([
      { reportType: 'Basel III Capital Adequacy', regulatoryBody: 'Federal Reserve', period: '2024-Q1', status: 'submitted', complianceScore: 95.5, findings: 'Capital ratios exceed minimum requirements', recommendations: 'Maintain current capital buffer strategy', dueDate: '2024-04-30', submittedAt: '2024-04-15' },
      { reportType: 'CECL Allowance Report', regulatoryBody: 'FASB/SEC', period: '2024-Q1', status: 'submitted', complianceScore: 92.0, findings: 'Allowance methodology aligns with CECL requirements', recommendations: 'Update loss rate assumptions for auto portfolio', dueDate: '2024-04-30', submittedAt: '2024-04-20' },
      { reportType: 'Fair Lending Analysis', regulatoryBody: 'CFPB', period: '2023-Annual', status: 'review', complianceScore: 88.5, findings: 'Minor disparities in approval rates for certain demographics', recommendations: 'Implement enhanced fair lending monitoring', dueDate: '2024-03-31' },
      { reportType: 'BSA/AML Compliance', regulatoryBody: 'FinCEN', period: '2024-Q1', status: 'submitted', complianceScore: 97.0, findings: 'SAR filing procedures compliant', recommendations: 'Enhance transaction monitoring thresholds', dueDate: '2024-04-15', submittedAt: '2024-04-10' },
      { reportType: 'Stress Test (DFAST)', regulatoryBody: 'Federal Reserve', period: '2024-Annual', status: 'draft', complianceScore: 90.0, findings: 'Institution passes severely adverse scenario', recommendations: 'Increase loss reserves for CRE portfolio', dueDate: '2024-06-30' },
      { reportType: 'CRA Compliance Report', regulatoryBody: 'OCC', period: '2023-Annual', status: 'submitted', complianceScore: 85.0, findings: 'Satisfactory CRA rating with opportunities for improvement', recommendations: 'Expand CDFI partnerships', dueDate: '2024-03-15', submittedAt: '2024-03-10' },
      { reportType: 'TILA/RESPA Audit', regulatoryBody: 'CFPB', period: '2024-Q1', status: 'review', complianceScore: 91.5, findings: 'Loan estimates delivered within timeframes', recommendations: 'Improve closing disclosure accuracy', dueDate: '2024-05-15' },
      { reportType: 'Cybersecurity Assessment', regulatoryBody: 'FFIEC', period: '2024-Q1', status: 'draft', complianceScore: 87.0, findings: 'Cybersecurity maturity at intermediate level', recommendations: 'Implement zero-trust architecture', dueDate: '2024-05-30' },
      { reportType: 'Liquidity Coverage Ratio', regulatoryBody: 'Federal Reserve', period: '2024-Q1', status: 'submitted', complianceScore: 96.0, findings: 'LCR exceeds minimum 100% requirement at 135%', recommendations: 'Optimize HQLA composition', dueDate: '2024-04-30', submittedAt: '2024-04-25' },
      { reportType: 'Volcker Rule Compliance', regulatoryBody: 'SEC/CFTC', period: '2023-Annual', status: 'submitted', complianceScore: 98.0, findings: 'No prohibited proprietary trading detected', recommendations: 'Update covered fund inventory', dueDate: '2024-03-31', submittedAt: '2024-03-20' },
      { reportType: 'GDPR Data Privacy', regulatoryBody: 'EU DPA', period: '2024-Q1', status: 'review', complianceScore: 82.0, findings: 'Data retention policies need updating', recommendations: 'Implement automated data deletion workflows', dueDate: '2024-05-15' },
      { reportType: 'HMDA Reporting', regulatoryBody: 'CFPB', period: '2023-Annual', status: 'submitted', complianceScore: 94.0, findings: 'LAR data quality meets standards', recommendations: 'Automate geocoding verification', dueDate: '2024-03-01', submittedAt: '2024-02-28' },
      { reportType: 'Model Risk Management', regulatoryBody: 'OCC/Fed', period: '2024-Q1', status: 'draft', complianceScore: 86.0, findings: 'Credit scoring model validation current', recommendations: 'Schedule champion-challenger testing', dueDate: '2024-06-15' },
      { reportType: 'Operational Risk Assessment', regulatoryBody: 'Basel Committee', period: '2024-Q1', status: 'review', complianceScore: 89.0, findings: 'Operational loss events within tolerance', recommendations: 'Enhance business continuity testing', dueDate: '2024-05-30' },
      { reportType: 'Consumer Complaints Report', regulatoryBody: 'CFPB', period: '2024-Q1', status: 'submitted', complianceScore: 93.0, findings: 'Complaint resolution within SLA targets', recommendations: 'Improve first-call resolution rate', dueDate: '2024-04-30', submittedAt: '2024-04-22' },
      { reportType: 'Third-Party Risk Review', regulatoryBody: 'OCC', period: '2024-Q1', status: 'draft', complianceScore: 84.0, findings: 'Critical vendor assessments current', recommendations: 'Add fourth-party risk monitoring', dueDate: '2024-06-30' },
    ]);
    console.log('Regulatory Reports seeded');

    // Seed Collateral (16 items)
    await Collateral.bulkCreate([
      { applicantId: 1, type: 'Residential Property', description: '3BR/2BA Single Family Home, 2200 sqft', estimatedValue: 450000, verifiedValue: 435000, loanToValue: 66.7, condition: 'Excellent', location: 'New York, NY', lastAppraisalDate: '2024-01-15', status: 'active' },
      { applicantId: 2, type: 'Residential Property', description: '2BR/2BA Condo, Downtown, 1400 sqft', estimatedValue: 680000, verifiedValue: 670000, loanToValue: 67.2, condition: 'Excellent', location: 'San Francisco, CA', lastAppraisalDate: '2024-02-10', status: 'active' },
      { applicantId: 3, type: 'Commercial Property', description: 'Office Building, 15000 sqft', estimatedValue: 2500000, verifiedValue: 2350000, loanToValue: 85.1, condition: 'Good', location: 'Chicago, IL', lastAppraisalDate: '2023-11-20', status: 'active' },
      { applicantId: 4, type: 'Vehicle', description: '2024 Toyota Camry XSE', estimatedValue: 35000, verifiedValue: 33000, loanToValue: 84.8, condition: 'New', location: 'Austin, TX', lastAppraisalDate: '2024-03-01', status: 'active' },
      { applicantId: 8, type: 'Residential Property', description: '4BR/3BA Colonial, 3500 sqft', estimatedValue: 750000, verifiedValue: 740000, loanToValue: 47.3, condition: 'Excellent', location: 'Boston, MA', lastAppraisalDate: '2024-01-25', status: 'active' },
      { applicantId: 9, type: 'Residential Property', description: '3BR/2BA Ranch, 1800 sqft', estimatedValue: 380000, verifiedValue: 370000, loanToValue: 75.0, condition: 'Good', location: 'Portland, OR', lastAppraisalDate: '2023-12-15', status: 'active' },
      { applicantId: 11, type: 'Business Equipment', description: 'CNC Machinery and Tools', estimatedValue: 250000, verifiedValue: 220000, loanToValue: 45.5, condition: 'Good', location: 'Atlanta, GA', lastAppraisalDate: '2024-02-20', status: 'active' },
      { applicantId: 13, type: 'Vehicle', description: '2024 BMW X5 xDrive40i', estimatedValue: 65000, verifiedValue: 62000, loanToValue: 72.6, condition: 'New', location: 'Dallas, TX', lastAppraisalDate: '2024-03-05', status: 'active' },
      { applicantId: 15, type: 'Residential Property', description: '5BR/4BA Estate, 5000 sqft', estimatedValue: 1200000, verifiedValue: 1150000, loanToValue: 43.5, condition: 'Excellent', location: 'San Diego, CA', lastAppraisalDate: '2024-02-01', status: 'active' },
      { applicantId: 5, type: 'Investment Portfolio', description: 'Diversified stock and bond portfolio', estimatedValue: 500000, verifiedValue: 480000, loanToValue: 31.3, condition: 'N/A', location: 'Brokerage Account', lastAppraisalDate: '2024-03-10', status: 'active' },
      { applicantId: 11, type: 'Accounts Receivable', description: 'Outstanding invoices from enterprise clients', estimatedValue: 180000, verifiedValue: 150000, loanToValue: 66.7, condition: 'Current', location: 'Atlanta, GA', lastAppraisalDate: '2024-03-01', status: 'active' },
      { applicantId: 3, type: 'Inventory', description: 'Consulting firm technology inventory', estimatedValue: 85000, verifiedValue: 70000, loanToValue: 285.7, condition: 'Good', location: 'Chicago, IL', lastAppraisalDate: '2024-01-10', status: 'under_review' },
      { applicantId: 2, type: 'Vehicle', description: '2023 Tesla Model S Plaid', estimatedValue: 90000, verifiedValue: 82000, loanToValue: 18.3, condition: 'Excellent', location: 'San Francisco, CA', lastAppraisalDate: '2024-02-15', status: 'active' },
      { applicantId: 15, type: 'Boat/Marine', description: '42ft Sailing Yacht', estimatedValue: 350000, verifiedValue: 320000, loanToValue: 156.3, condition: 'Good', location: 'San Diego Marina', lastAppraisalDate: '2023-10-20', status: 'active' },
      { applicantId: 8, type: 'Art Collection', description: 'Contemporary art collection, 12 pieces', estimatedValue: 200000, verifiedValue: 175000, loanToValue: 200.0, condition: 'Excellent', location: 'Private Vault, Boston', lastAppraisalDate: '2023-09-15', status: 'active' },
      { applicantId: 13, type: 'Life Insurance', description: 'Whole life policy cash value', estimatedValue: 150000, verifiedValue: 148000, loanToValue: 30.4, condition: 'N/A', location: 'Policy #LI-445566', lastAppraisalDate: '2024-01-01', status: 'active' },
    ]);
    console.log('Collateral seeded');

    // Seed Early Warnings (16 items)
    await EarlyWarning.bulkCreate([
      { applicantId: 3, warningType: 'Payment Delinquency', severity: 'high', triggerMetric: 'Days Past Due', triggerValue: 45, thresholdValue: 30, description: 'Missed two consecutive payments', recommendedAction: 'Contact borrower, initiate collections process', status: 'active' },
      { applicantId: 6, warningType: 'Credit Score Drop', severity: 'medium', triggerMetric: 'Credit Score Change', triggerValue: -65, thresholdValue: -50, description: 'Credit score dropped from 760 to 695', recommendedAction: 'Review account, request updated financials', status: 'active' },
      { applicantId: 7, warningType: 'Income Reduction', severity: 'critical', triggerMetric: 'Income Change %', triggerValue: -60, thresholdValue: -25, description: 'Part-time employment with significant income drop', recommendedAction: 'Restructure loan terms, consider forbearance', status: 'active' },
      { applicantId: 12, warningType: 'Overleveraging', severity: 'medium', triggerMetric: 'DTI Ratio', triggerValue: 52, thresholdValue: 45, description: 'New debt acquired pushing DTI above threshold', recommendedAction: 'Financial counseling referral', status: 'active' },
      { applicantId: 10, warningType: 'Employment Change', severity: 'low', triggerMetric: 'Employment Status', triggerValue: 1, thresholdValue: 1, description: 'Changed employers recently', recommendedAction: 'Monitor for income stability', status: 'acknowledged' },
      { applicantId: 16, warningType: 'Rapid Credit Inquiries', severity: 'medium', triggerMetric: 'Hard Inquiries (90d)', triggerValue: 8, thresholdValue: 5, description: '8 hard credit inquiries in 90 days', recommendedAction: 'Review for potential fraud or financial distress', status: 'active' },
      { applicantId: 4, warningType: 'Utilization Spike', severity: 'medium', triggerMetric: 'Credit Utilization %', triggerValue: 85, thresholdValue: 70, description: 'Credit utilization jumped to 85%', recommendedAction: 'Proactive outreach, offer consolidation', status: 'active' },
      { applicantId: 1, warningType: 'Market Risk', severity: 'low', triggerMetric: 'Industry Risk Index', triggerValue: 72, thresholdValue: 65, description: 'Tech sector showing elevated risk indicators', recommendedAction: 'Monitor sector trends', status: 'acknowledged' },
      { applicantId: 9, warningType: 'Property Value Decline', severity: 'medium', triggerMetric: 'Property Value Change %', triggerValue: -12, thresholdValue: -10, description: 'Collateral property value declined 12%', recommendedAction: 'Request updated appraisal', status: 'active' },
      { applicantId: 11, warningType: 'Cash Flow Deterioration', severity: 'high', triggerMetric: 'Cash Flow Ratio', triggerValue: 0.85, thresholdValue: 1.0, description: 'Business cash flow below coverage ratio', recommendedAction: 'Request updated business financials', status: 'active' },
      { applicantId: 14, warningType: 'Bankruptcy Risk', severity: 'critical', triggerMetric: 'Altman Z-Score', triggerValue: 1.2, thresholdValue: 1.8, description: 'Z-Score indicates high bankruptcy probability', recommendedAction: 'Accelerate collections, legal review', status: 'active' },
      { applicantId: 5, warningType: 'Account Dormancy', severity: 'low', triggerMetric: 'Days Since Activity', triggerValue: 120, thresholdValue: 90, description: 'No account activity for 120 days', recommendedAction: 'Customer engagement outreach', status: 'active' },
      { applicantId: 13, warningType: 'Regulatory Change', severity: 'medium', triggerMetric: 'Compliance Impact', triggerValue: 3, thresholdValue: 2, description: 'New regulations may impact loan terms', recommendedAction: 'Legal review of existing agreements', status: 'acknowledged' },
      { applicantId: 2, warningType: 'Geographic Risk', severity: 'low', triggerMetric: 'Area Risk Score', triggerValue: 68, thresholdValue: 60, description: 'Property area showing economic softening', recommendedAction: 'Monitor regional economic indicators', status: 'active' },
      { applicantId: 8, warningType: 'Insurance Lapse', severity: 'high', triggerMetric: 'Insurance Status', triggerValue: 0, thresholdValue: 1, description: 'Property insurance policy lapsed', recommendedAction: 'Force-place insurance, notify borrower', status: 'active' },
      { applicantId: 15, warningType: 'Interest Rate Risk', severity: 'medium', triggerMetric: 'Rate Sensitivity', triggerValue: 2.5, thresholdValue: 2.0, description: 'ARM approaching rate adjustment period', recommendedAction: 'Offer refinance options', status: 'active' },
    ]);
    console.log('Early Warnings seeded');

    // Seed Pricing Models (16 items)
    await PricingModel.bulkCreate([
      { name: 'Prime Personal Loan', loanType: 'Personal', baseRate: 5.0, riskPremium: 1.5, finalRate: 6.5, minCreditScore: 720, maxCreditScore: 850, minLoanAmount: 5000, maxLoanAmount: 50000, termMonths: 60, fees: 1.0, status: 'active' },
      { name: 'Standard Auto Loan', loanType: 'Auto', baseRate: 4.5, riskPremium: 2.0, finalRate: 6.5, minCreditScore: 680, maxCreditScore: 850, minLoanAmount: 10000, maxLoanAmount: 75000, termMonths: 72, fees: 0.5, status: 'active' },
      { name: 'Premium Mortgage 30Y', loanType: 'Mortgage', baseRate: 6.5, riskPremium: 0.5, finalRate: 7.0, minCreditScore: 740, maxCreditScore: 850, minLoanAmount: 200000, maxLoanAmount: 2000000, termMonths: 360, fees: 0.75, status: 'active' },
      { name: 'Standard Mortgage 30Y', loanType: 'Mortgage', baseRate: 6.5, riskPremium: 1.0, finalRate: 7.5, minCreditScore: 680, maxCreditScore: 739, minLoanAmount: 100000, maxLoanAmount: 750000, termMonths: 360, fees: 1.0, status: 'active' },
      { name: 'Small Business Term', loanType: 'Business', baseRate: 7.0, riskPremium: 2.5, finalRate: 9.5, minCreditScore: 650, maxCreditScore: 850, minLoanAmount: 25000, maxLoanAmount: 500000, termMonths: 84, fees: 1.5, status: 'active' },
      { name: 'SBA 7(a) Loan', loanType: 'SBA', baseRate: 6.0, riskPremium: 2.0, finalRate: 8.0, minCreditScore: 620, maxCreditScore: 850, minLoanAmount: 50000, maxLoanAmount: 5000000, termMonths: 120, fees: 2.0, status: 'active' },
      { name: 'Student Refi', loanType: 'Student', baseRate: 4.0, riskPremium: 1.0, finalRate: 5.0, minCreditScore: 700, maxCreditScore: 850, minLoanAmount: 10000, maxLoanAmount: 200000, termMonths: 120, fees: 0, status: 'active' },
      { name: 'HELOC Variable', loanType: 'HELOC', baseRate: 7.5, riskPremium: 1.0, finalRate: 8.5, minCreditScore: 680, maxCreditScore: 850, minLoanAmount: 25000, maxLoanAmount: 500000, termMonths: 240, fees: 0.5, status: 'active' },
      { name: 'Subprime Auto', loanType: 'Auto', baseRate: 4.5, riskPremium: 10.0, finalRate: 14.5, minCreditScore: 500, maxCreditScore: 619, minLoanAmount: 5000, maxLoanAmount: 30000, termMonths: 60, fees: 2.5, status: 'active' },
      { name: 'BNPL Standard', loanType: 'BNPL', baseRate: 0, riskPremium: 0, finalRate: 0, minCreditScore: 580, maxCreditScore: 850, minLoanAmount: 50, maxLoanAmount: 3000, termMonths: 3, fees: 0, status: 'active' },
      { name: 'Equipment Finance', loanType: 'Equipment', baseRate: 6.0, riskPremium: 2.0, finalRate: 8.0, minCreditScore: 650, maxCreditScore: 850, minLoanAmount: 25000, maxLoanAmount: 2000000, termMonths: 84, fees: 1.0, status: 'active' },
      { name: 'Bridge Loan', loanType: 'Bridge', baseRate: 8.0, riskPremium: 4.0, finalRate: 12.0, minCreditScore: 680, maxCreditScore: 850, minLoanAmount: 100000, maxLoanAmount: 5000000, termMonths: 12, fees: 2.0, status: 'active' },
      { name: 'Credit Card Standard', loanType: 'Credit Card', baseRate: 15.0, riskPremium: 5.0, finalRate: 20.0, minCreditScore: 650, maxCreditScore: 749, minLoanAmount: 500, maxLoanAmount: 25000, termMonths: 0, fees: 0, status: 'active' },
      { name: 'Credit Card Premium', loanType: 'Credit Card', baseRate: 12.0, riskPremium: 3.0, finalRate: 15.0, minCreditScore: 750, maxCreditScore: 850, minLoanAmount: 5000, maxLoanAmount: 100000, termMonths: 0, fees: 95, status: 'active' },
      { name: 'Construction Loan', loanType: 'Construction', baseRate: 7.5, riskPremium: 3.0, finalRate: 10.5, minCreditScore: 700, maxCreditScore: 850, minLoanAmount: 200000, maxLoanAmount: 10000000, termMonths: 18, fees: 1.5, status: 'active' },
      { name: 'Agricultural Operating', loanType: 'Agricultural', baseRate: 6.5, riskPremium: 2.0, finalRate: 8.5, minCreditScore: 620, maxCreditScore: 850, minLoanAmount: 10000, maxLoanAmount: 1000000, termMonths: 12, fees: 1.0, status: 'active' },
    ]);
    console.log('Pricing Models seeded');

    console.log('\n✅ All seed data loaded successfully!');
    process.exit(0);
  } catch (err) {
    console.error('Seed error:', err);
    process.exit(1);
  }
}

seed();
